# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Al Banna
tagline:          'Corat Coret'
description:      'Pemilik Toko <a href="http://zazakhuna.com" target="_blank">zazakhuna</a> yang Pengguna Manjaro juga. Kicauan di <a href="https://twitter.com/zazakhuna" target="_blank">@zazakhuna</a>.'
url:              http://blog.zazakhuna.com
baseurl:          /

author:
  name:           'Hasan Al Banna'
  url:            https://twitter.com/zazakhuna

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
